model: scfoundation
task_name: EMT

data:
  input_path: ./data/raw/emt.h5ad

external:
  homo_path: ./data/external/scFoundation/homo_id.txt
  gene_list_path: ./data/external/scFoundation/OS_scRNA_gene_index.19264.tsv

preprocess:
  gene_key: index
  species: human

embedding: # 参考scfoundation参数设置
  model_path: ./pretrained_models/scFoundation/model/models/models.ckpt
  pre_normalized: F # 数据是否进行过normalized
  select_col: ["Time", "Phase"] # 需要保存哪些列的meta信息, 如果为空保存所有obs信息

evaluate:  
  emb_dim: 768
  labels: ['Phase', 'Time']
  umap_keys: ['Phase', 'Time']
  batch_key: 'Phase'

