model: scgpt
task_name: EMT

data:
  input_path: ./data/raw/emt.h5ad

preprocess:
  gene_key: index
  species: human


embedding: 
  model_path: ./pretrained_models/scGPT/scgpt_human
  setting: 'zeroshot'
  select_col: ["Time", "Phase"]  # obs columns to keep in export; empty = all obs
  batch_size: 64

evaluate:
  emb_dim: 512
  labels: ['Phase', 'Time']
  umap_keys: ['Phase', 'Time']
  batch_key: 'Phase'

