model: geneformer
task_name: EMT

data:
  input_path: ./data/raw/emt.h5ad

preprocess:
  gene_key: name
  species: human
  custom_attr_name_dict: # selected col
    "Time": "Time"
    "Phase": "Phase"

embedding: 
  model_path: '/macroverse/public/zhouxy/pretrained_models/Geneformer/Geneformer-V2-104M' # huggingface pretrained model path
  setting: 'zeroshot'
  select_col: ["Time", "Phase"] # meta info to save
  batch_size: 64

evaluate:
  emb_dim: 768 # hidden_dim of embedding
  labels: ['Phase', 'Time']
  umap_keys: ['Phase', 'Time'] # for plot and eval
  batch_key: 'Phase' # for avgBIO computation

