model: geneformer
task_name: EMT

data:
  input_path: ./data/raw/emt.h5ad
  external:
    homo_path: ./data/external/homo_id.txt # homologues conversion file and ensembl id to gene symbol

preprocess:
  gene_key: index # gene name or ensembl id
  species: human

embedding: 
  # Point to your local weights (e.g. after downloading Geneformer V2 104M)
  model_path: ./pretrained_models/Geneformer/Geneformer-V2-104M
  setting: 'zeroshot'
  batch_size: 64

evaluate:
  emb_dim: 768 # hidden_dim of embedding
  umap_keys: ['Phase', 'Time'] # for plot and eval
  batch_key: 'Phase' # for avgBIO computation

