model: scfoundation
task_name: EMT

data:
  input_path: ./data/raw/emt.h5ad

external:
  homo_path: ./data/external/scFoundation/homo_id.txt
  gene_list_path: ./data/external/scFoundation/OS_scRNA_gene_index.19264.tsv

preprocess:
  gene_key: index
  species: human

embedding:  # scFoundation embedding settings
  model_path: ./pretrained_models/scFoundation/model/models/models.ckpt
  pre_normalized: F  # whether input was already normalized
  select_col: ["Time", "Phase"]  # obs columns to keep; empty = all obs

evaluate:  
  emb_dim: 768
  labels: ['Phase', 'Time']
  umap_keys: ['Phase', 'Time']
  batch_key: 'Phase'

