model: uce
task_name: EMT

data:
  input_path: ./data/raw/emt.h5ad

preprocess:
  species: human

embedding: 
  model_path: ./pretrained_models/UCE
  species: human
  batch_size: 128
  nlayers: 33

evaluate:
  labels: ['Phase', 'Time']
  umap_keys: ['Phase', 'Time']
  batch_key: 'Time'

