model: genecompass
task_name: EMT

data:
  input_path: ./data/raw/emt.h5ad

external:
  gene_id_to_name_path: ./pretrained_models/GeneCompass/prior_knowledge/gene_list/Gene_id_name_dict_human_mouse.pickle
  gene_token_dict_path: ./pretrained_models/GeneCompass/prior_knowledge/human_mouse_tokens.pickle
  gene_median_dict_path: ./pretrained_models/Geneformer/gene_median_dictionary_gc104M.pkl


preprocess:
  gene_key: index
  species: human


embedding: 
  model_path: ./pretrained_models/GeneCompass/pretrained_models/GeneCompass_Base
  setting: 'zeroshot'
  select_col: ["Time", "Phase"]  # obs columns to keep; empty = all obs
  batch_size: 64

evaluate:
  emb_dim: 768
  labels: ['Phase', 'Time']
  umap_keys: ['Phase', 'Time']
  batch_key: 'Phase'

