align_strategies:
- gpa_consensus
dataset:
  name: EMT
  path: ./data/embeddings/EMT/benchmark.h5ad # integrated embeddings path
  pseudotime_key: Pseudotime
  ref_key: hvg
  test_times:
  - 0
  time_key: time
  train_times:
  - 1
  - 2
  - 3
dynamic_methods:
- engine_config:
    generate_script: ./DeepRUOTv2/infer_RUOT.py
    num_runs: 10
    python_exec: python
    run_pattern: sde_run_*.npz
    template_cfg: ./DeepRUOTv2/config/emt_config.yaml
    train_script: ./DeepRUOTv2/train_RUOT.py
  engine_type: deepruot
  name: deepruot
  params:
    dim:
    - 50
    - 10
    - 5
    - 20
    otmode:
    - ruot
    - dot
    - sb
    - uot

metrics:
- tcvc
- pseudotime
- w1tmv

models: # models to benchmark
- hvg
- genecompass
- uce
- scgpt
- scfoundation
- geneformer
options:
  max_workers: 6
  skip_existing: true
paths:
  artifacts: ./artifacts/gpa/EMT_holdt0 # save alignment artifacts
  benchmark_results: ./results/gpa/EMT_holdt0 # save benchmark results
  input_dir: ./data/deepruot_input/EMT # save processed data for DeepRUOT
  results_dir: ./results/dynamic_results/EMT # save dynamic results
